server:
  port: 8080

spring:
  main:
    allow-circular-references: true

  application:
    name: expense-tracker

  flyway:
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/expense-tracker
    username: postgres
    password: 7020
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # validate schema against DB (safe for prod)
    show-sql: true         # log SQL in console (good for dev)
    properties:
      hibernate:
        format_sql: true   # pretty print SQL

  # Mongo support (only if you switch to Mongo)
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/expense-tracker

# Logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Profile-based config (switch between Postgres and Mongo)
app:
  db:
    type: ${DB_TYPE:postgres}   # default postgres, can override with env
  jwt:
    secret: chinmay-and-batman-never-seen-in-room-together #do not keep secret here, i need to change it
    access-token-expiration: 900000      # 15 min in ms
    refresh-token-expiration: 604800000  # 7 days in ms

