server:
  port: 8080

spring:
  application:
    name: expense-tracker

  flyway:
    baseline-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/expense-tracker
    username: postgres
    password: 7020
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate   # validate schema against DB (safe for prod)
    show-sql: true         # log SQL in console (good for dev)
    properties:
      hibernate:
        format_sql: true   # pretty print SQL

  # Mongo support (only if you switch to Mongo)
  data:
    mongodb:
      uri: mongodb://localhost:27017/expense-tracker

# Logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Profile-based config (switch between Postgres and Mongo)
app:
  db:
    type: ${DB_TYPE:postgres}   # default postgres, can override with env
